name: Scrape

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install modules
        run: pip install BeautifulSoup4 markdownify

      - name: Scrape
        run: python scrape.py
        
      - name: Push
        run: |
          git add .
          git commit -sam "Updated supplements automatically!" || true
          git push || true
